document.write('<li><a href="index.html">Item </a></li>')
document.write('<li><a href="index.html"  aria-haspopup="true" class="submenu">Menu</a>')
document.write('<ul aria-label="submenu">')
document.write('<li><a href="index.html">Long Title Item Thing</a></li>')
document.write('<li><a href="index.html">Menu 2</a></li>')
document.write('</ul>')
document.write('</li>')
document.write('<li><a href="index.html">Long Title Item </a></li>')
document.write('<li><a href="index.html">Item </a></li>')
document.write('<li><a href="index.html">Item </a></li>')