document.write('<li><a href="index.html">Hidden Menu</a></li>')
document.write('<li><a href="index.html">This</a></li>')
document.write('<li><a href="index.html" aria-haspopup="true" class="submenu">That</a>')
document.write('  <ul aria-label="submenu">')
document.write('    <li><a href="index.html">Long Title Item Thing</a></li>')
document.write('    <li><a href="index.html">Menu 2</a></li>')
document.write('    <li><a href="index.html">Menu 2</a></li>')
document.write('    <li><a href="index.html">Menu 2</a></li>')
document.write('    <li><a href="index.html">Menu 2</a></li>')
document.write('   <li><a href="index.html">Menu 2</a></li>')
document.write('  </ul>')
document.write('</li>')
document.write('<li><a href="index.html" aria-haspopup="true" class="submenu">Other</a>')
document.write(' <ul aria-label="submenu">')
document.write('   <li><a href="index.html">Long Title Item Thing</a></li>')
document.write('    <li><a href="index.html">Menu 2</a></li>')
document.write('  </ul>')
document.write('</li>')
document.write('<li><a href="index.html">Long Title Item Title</a></li>')
document.write('<li><a href="index.html">Steve</a></li>')
document.write('<li><a href="index.html">Not Steve</a></li>')