document.write('<li><a href="#">Home</a></li>')
document.write('<li class="dropdown">')
document.write('<button type="button" class="dropdown__title" aria-expanded="false" aria-controls="sweets-dropdown">Dropdown</button>')
document.write('<ul class="dropdown__menu" id="sweets-dropdown">')
document.write('<li><a href="#">this</a></li>')
document.write('<li><a href="#">that</a></li>')
document.write('<li><a href="#">other</a></li>')
document.write('</ul>')
document.write('</li>')
document.write('<li><a href="#">Regular</a></li>')
document.write('<li><a href="#">Stuff</a></li>')

